// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usecase

import (
	"github.com/wadda0714/My_AI_Assistant/infra/query"
)

// Injectors from wire.go:

func GeneratedInitializeAssistantDI() Assistant {
	queryAssistant := query.NewAssistantQuery()
	usecaseAssistant := NewAssistant(queryAssistant)
	return usecaseAssistant
}
